data: # Configuration: dataset spliting for train and test 
  test_size: 0.2
  random_state: 42
  target_column: 'status'

model: # Model training configuration
  gradient_boosting: # Gradient Boosting 
    n_estimators: 100
    learning_rate: 0.1
    random_state: 42
    max_depth: 3

train:  
  epochs: 22